### ISSUE TITLE
Problème affichage suite ajout d'une cover

### ISSUE THREAD

**Issue by ghost** [bkfox/aircox#7]
J'ai ajouté une image pour l'émission (programs) Source: https://aircox.radiocampus.be/programs/source/

Et ce la décale les entrées texte sur la gauche de cette page: https://aircox.radiocampus.be/programs/?  :eyes: :

**Comment by bkfox** [comment]
Il s'agit d'un comportement tout à fait normal. Du point de vue du design et de la compréhension visuelle, il est plutôt préférable de garder les textes des titres/préambule alignés verticalement.

Ceci dit, je me dis aussi que tant qu'il n'y a pas de cover dans une liste cela n'est peut-être pas nécessaire de réserver l'espace qui leur est alloué.
