### ISSUE TITLE
Fin du site actuel prévue pour Juin 2020

### ISSUE THREAD

**Issue by ghost** [bkfox/aircox#8]
Est-ce que tu penses qu'Aircox pourra passer en prod (ou plus ou moins) d'ici le mois de mais ou juin ?

C'est une question parce que le serveur qui héberge le wordpress sera coupé en juin par la VUB.

:crossed_fingers:

**Comment by bkfox** [comment]
Salut,
Concernant les problématiques relative à la mise en prod ou spécifique à Radio Campus, on peut plutôt garder ça par mail, s'agissant ici plutôt du dépot ce qui est spécifique à l'application en elle-même.

Je te réponds par mail juste après :)
